-- Idempotent seed for auctions1 (BidStream). Auction #6 is CLOSED with
-- end_time > 5 days ago and is intentionally eligible for the nightly cleanup.
INSERT INTO auctions1 (id, title, description, seller_id, starting_price, current_price, highest_bid_id, highest_bidder_id, start_time, end_time, status, created_at) VALUES
(1,  'Sony Alpha A7 III Mirrorless Camera', 'Full-frame mirrorless camera body with 24.2MP sensor, includes box and original accessories.', 2, 1200.00, 1200.00, NULL, NULL, NOW() + INTERVAL '2 days',  NOW() + INTERVAL '9 days',  'PENDING', NOW() - INTERVAL '1 day'),
(2,  'MacBook Pro 14-inch M3 (2023)',       'Apple MacBook Pro 14 with M3 chip, 16GB RAM, 512GB SSD. Battery health 92%.',              2, 1800.00, 2200.00, 6,    6,    NOW() - INTERVAL '3 days', NOW() + INTERVAL '4 days',  'ACTIVE',  NOW() - INTERVAL '4 days'),
(3,  'Canon EF 70-200mm f/2.8L IS III Lens', 'Professional telephoto zoom lens in excellent condition with hood, caps and case.',      2, 900.00,  900.00,  NULL, NULL, NOW() - INTERVAL '1 day',  NOW() + INTERVAL '6 days',  'ACTIVE',  NOW() - INTERVAL '2 days'),
(4,  'Omega Seamaster 300 Diver Watch',     'Automatic dive watch, 41mm, includes papers and box, serviced 2025.',                      3, 3200.00, 3350.00, 8,    7,    NOW() - INTERVAL '5 days', NOW() + INTERVAL '2 days',  'ACTIVE',  NOW() - INTERVAL '6 days'),
(5,  'Rolex Datejust 41 Blue Dial Watch',   'Datejust 41 with fluted bezel and jubilee bracelet, full set with warranty card.',        3, 6500.00, 6900.00, 18,   9,    NOW() - INTERVAL '10 days', NOW() - INTERVAL '3 days', 'CLOSED',  NOW() - INTERVAL '11 days'),
(6,  '1969 Ford Mustang Mach 1 Classic',    'Restored 1969 Mustang Mach 1, 351 Windsor V8, 4-speed, California car.',                4, 28000.00, 31000.00, 20,   6,    NOW() - INTERVAL '14 days', NOW() - INTERVAL '7 days', 'CLOSED',  NOW() - INTERVAL '15 days'),
(7,  'Tesla Model 3 Long Range 2021',       '2021 Tesla Model 3 Long Range AWD, 45,000 miles, autopilot, no accidents.',              4, 31000.00, 31000.00, NULL, NULL, NOW() - INTERVAL '12 days', NOW() - INTERVAL '2 days', 'EXPIRED', NOW() - INTERVAL '13 days'),
(8,  'Bose QuietComfort 45 Headphones',     'Wireless noise-cancelling headphones, comes with case and cables.',                      5, 250.00,  280.00,  11,   8,    NOW() - INTERVAL '6 days', NOW() + INTERVAL '1 day',  'ACTIVE',  NOW() - INTERVAL '7 days'),
(9,  'Patek Philippe Nautilus 5711 Watch',  'Nautilus 5711 in stainless steel, blue dial, box and papers included.',                 3, 45000.00, 45000.00, NULL, NULL, NOW() + INTERVAL '5 days',  NOW() + INTERVAL '12 days', 'PENDING', NOW() - INTERVAL '1 day'),
(10, 'Leica Q2 Digital Camera',             'Compact full-frame camera with 28mm Summilux lens, excellent condition.',               2, 4200.00, 4500.00, 22,   8,    NOW() - INTERVAL '8 days', NOW() - INTERVAL '2 days', 'CLOSED',  NOW() - INTERVAL '9 days'),
(11, 'Ducati Monster 937 Motorcycle',       '2022 Ducati Monster 937, 3,200 miles, full service history, clean title.',             4, 9800.00, 10500.00, 15,   9,    NOW() - INTERVAL '2 days', NOW() + INTERVAL '5 days',  'ACTIVE',  NOW() - INTERVAL '3 days'),
(12, 'Kenwood Chef XL Stand Mixer',         'Chef XL KVL8300S stand mixer, rarely used, all attachments included.',                   3, 180.00,  195.00,  23,   7,    NOW() - INTERVAL '6 days', NOW() - INTERVAL '1 day',  'CLOSED',  NOW() - INTERVAL '7 days')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('auctions1', 'id'), (SELECT COALESCE(MAX(id), 1) FROM auctions1));
